### ISSUE TITLE
Ef not generating

### ISSUE THREAD

**Issue by pimboden** [thomasduft/microwf#11]
Hello.
I forked your project, to test it (and eventually add some PRs if needed).
I'm trying to add a complete new Workflow, it seams really easy to do. But when I was almost finished i got stuck because I can't generate the migration.
I get the error

> Unable to create an object of type 'DomainContext'. For the different patterns supported at
> design time, see...
> ...
> System.MissingMethodException: No parameterless constructor defined for this object. ....
> ....
> at Microsoft.EntityFrameworkCore.Design.Internal.DbContextOperations.<>c__DisplayClass12_3.<FindContextTypes>b__13()

Whenever I execute 
`dotnet ef migrations add SoftwareRequest001 -c DomainContext`

Im executing it under microwf/samples/WebApi 
Am I doing something wrong, or have you any clue what this might be?

BTW: Nice work!
I'm not using the docker, because sadly my company doesn't allow us yet to install docker. I will thou try your solution on my ubunto private PC

**Comment by thomasduft** [comment]
Hi
You are right. I can confirm that the ef migrations are broken in the WebApi sample project. Sorry, must have been messed it up.
In the meantime I created a StepperApi sample that serves more as a starting point. I tested the migrations there and it seems to work ;-). I try to fix it ASAP.
Greets Thomas
