### ISSUE TITLE
Login And Password

### ISSUE THREAD

**Issue by Hamza23579** [thomasduft/microwf#14]
Hi Thomas,
How can I authenticate from the login page ?
Thank you.

**Comment by thomasduft** [comment]
Hi there

The samples provide 3 users Alice, Bob and Admin that all have the password "password" ;-).

You can see them here: https://github.com/thomasduft/microwf/blob/2e910a3d8b08203e2aad198d8b679d6a8e1f2990/samples/WebApi/Identity/Config.cs#L72

Greets Thomas
