### ISSUE TITLE
Feature Request - Support for Child Tasks 

### ISSUE THREAD

**Issue by saikiranmandhala** [thomasduft/microwf#20]
Scenario:
1. Trainee Creates record (Parent Record#1 - Action: New; Status: New)
2. Trainee Completes work and submits (Parent Record#1 - Action: Submit; Status: Pending for Review)
3. Floor Manager Review Task gets created automatically. (Child Record#11 - Status: New)
4. Branch Manager Review Task gets created automatically. (Child Record#12 - Status: New)
5. Floor Manager approves the review task. (Child Record#11 - Action: Approve; Status: Approved)
5. Branch Manager approves the review task. As all the tasks are approved the parent case status changes to Approved (Child Record#12 - Action: Approve; Status: Approved; Parent Record#1 - Status: Approved)

**Comment by thomasduft** [comment]
Hi, I don't see the necessity to design child task in your sample. Imagine you have the following entity:
```csharp
public class MyEntity : IAssignableWorkflow
{
  ...
  public bool FloorManagerApproved { get; set;}
  public bool BranchManagerApproved { get; set;}
  ...
}
```
With this information you could design a "Workflow" that calls the steps in a sequence and update the entity accordingly as an example.

Another approach would be that you design 3 Workflows for each of the required personas and call the appropriate logic within the Transition-Logic of the "Trainee"-workflow.

Hope my ideas can help a bit.

Have a nice day
