### ISSUE TITLE
Dynamic Users from database.

### ISSUE THREAD

**Issue by determinate** [thomasduft/microwf#6]
Hello Thomas!
I want to know how i can create dynamic mapping users form database and context. Thank you. And how i can change it to dynamic

**Comment by thomasduft** [comment]
Hi 
Can you provide a bit more specific information? What exactly is your use case? Do you want to load users from a users table from your database?

In the samples WebApi project I am making use of [IdentityServer](https://identityserver.io/) with an InMemory-Users collection. If you try to load users from a database, then you should definitely have a look into IdentityServer. Additionally to that you will very likely provide your implementation of a [`IUserWorkflowMappingService`](https://github.com/thomasduft/microwf/blob/3f007d618e04d1d3e84213eb06e0783d77b305b1/src/microwf.AspNetCoreEngine/Services/UserWorkflowMappingService.cs#L23). Just make sure you register it in the ServiceCollection in your Startup.cs file after the [`AddWorkflowEngineServices`](https://github.com/thomasduft/microwf/blob/3f007d618e04d1d3e84213eb06e0783d77b305b1/samples/WebApi/Startup.cs#L129) call. This way your implementation will overwrite the [default implementation](https://github.com/thomasduft/microwf/blob/3f007d618e04d1d3e84213eb06e0783d77b305b1/src/microwf.AspNetCoreEngine/Services/UserWorkflowMappingService.cs#L41).

Side note: The entire authentication and authorization is built on top of the [ASP.NET Core Identity](https://docs.microsoft.com/en-us/aspnet/core/security/authentication/identity?view=aspnetcore-2.2&tabs=visual-studio) and [ASP.NET Core Authorization](https://docs.microsoft.com/en-us/aspnet/core/security/authorization/introduction?view=aspnetcore-2.2) functionality. As long as you build your user store on top of that you should be good to go. The user then gets resolved in the [`UserContextService`](https://github.com/thomasduft/microwf/blob/3f007d618e04d1d3e84213eb06e0783d77b305b1/src/microwf.AspNetCoreEngine/Services/UserContextService.cs#L14). 

Hope this helps. If I find time next month I will create a sample project where I am using such an approach.

Greets, Thomas

**Comment by determinate** [comment]
About IUserWorkflowMappingService. It was like  [This Sample Workflow Mapping](https://github.com/thomasduft/microwf/blob/3f007d618e04d1d3e84213eb06e0783d77b305b1/samples/WebApi/Startup.cs#L132), To define this mapping, i mast to do like this:
`public class UserMappingService : IUserWorkflowMappingService
  {
    private UserManager<User> _userManager { get; set; }
    private UserWorkflowMappingsStore _workflowStore { get; set; }
    
    public UserMappingService(UserManager<User> user, UserWorkflowMappingsStore wf)
    {
      this._userManager = user;
      this._workflowStore = wf;
      foreach (var u in _userManager.Users.ToList()){
        this._workflowStore.Workflows.ToList().Add(new UserWorkflowMapping()
        {
          UserName = u.UserName,
          WorkflowDefinitions = new List<string>()
          {
            SampleWorkflow.TYPE
          }
        });
      }
    }
    public IEnumerable<IWorkflowDefinition> Filter(IEnumerable<IWorkflowDefinition> workflowDefinitions)
    {
      throw new NotImplementedException();
    }`
or create another database table to store this mappings? 
Thanks very Much Thomas!
Sincerly Mike!

**Comment by thomasduft** [comment]
The extension method [`AddTestUserWorkflowMappings`](https://github.com/thomasduft/microwf/blob/3f007d618e04d1d3e84213eb06e0783d77b305b1/samples/WebApi/Startup.cs#L132) in the samples WebApi project is just for demo purposes. In a real application you can omit it. Instead, you need to provide an implementation of the `IUserWorkflowMappingService` like you did. The interesting bit of this interface would then be your implementation of the `Filter` method. It is not meant to throw a `NotImplementedException` ;-).

You are on the right track. Make use of the DI system an inject whatever you need in order to satisfy your needs. I guess in  your case I would create a database table (entity) where you store your mappings and read them from the database. In my sample I just configured the mappings in the appsettings.json file because I did not want to create another service and entities etc...

Hope that helps...

**Comment by determinate** [comment]
I have this error when i try like [this](https://github.com/thomasduft/microwf/issues/6#issuecomment-495567936), what is problem? 
![image](https://user-images.githubusercontent.com/15633523/58367958-7a029900-7f07-11e9-9afe-c0f85aa9dd0b.png)


Thank you, 
sincerly Mike

**Comment by thomasduft** [comment]
You need to make sure that your UserWorkflowMappingStore is registered within the ServiceProvider (DI container) during the bootstrap phase. If you forgot to do that the DI container won't be able to resolve it. The above error says it very clearly "Unable to resolve service for type...".

Another possibility is that you still have [this](https://github.com/thomasduft/microwf/blob/3f007d618e04d1d3e84213eb06e0783d77b305b1/samples/WebApi/Startup.cs#L132) call present. You should remove it in your application.

**Comment by determinate** [comment]
So I need to create my own class that ingerits from UserWorkflowMappingStore  and register it in startup.cs? i understand right way?

**Comment by determinate** [comment]
Hello Thomas!
I have some errors getting to register my custom workflow, 
```json
"Workflows": {
    "Types": [
      {
        "Type": "HolidayApprovalWorkflow",
        "Title": "Holiday",
        "Description": "Simple holiday approval process.",
        "Route": "holiday"
      },
      {
        "Type": "IssueTrackingWorkflow",
        "Title": "Issue",
        "Description": "Simple issue tracking process.",
        "Route": "issue"
      },
      {
        "Type": "StepperWorkflow",
        "Title": "Stepper",
        "Description": "Dummy workflow to test workflow processor",
        "Route": ""
      },
      {
        "Type": "SampleWorkflow",
        "Title": "Sample",
        "Description": "Dummy workflosa",
        "Route": ""
      }]
}
```
added my files 
![image](https://user-images.githubusercontent.com/15633523/58373423-f8832900-7f4f-11e9-92e5-7854d657763b.png)

and wirte in this code 
```csharp
private WorkflowConfiguration CreateWorkflowConfiguration()
    {
      return new WorkflowConfiguration
      {
        Types = new List<WorkflowType> {
          new WorkflowType {
            Type = "HolidayApprovalWorkflow",
            Title = "Holiday",
            Description = "Simple holiday approval process.",
            Route = "holiday"
          },
          new WorkflowType {
            Type = "IssueTrackingWorkflow",
            Title = "Issue",
            Description = "Simple issue tracking process.",
            Route = "issue"
          },
          new WorkflowType {
            Type = "StepperWorkflow",
            Title = "Stepper",
            Description = "Dummy workflow to test workflow processor.",
            Route = ""
          },
          new WorkflowType {
            Type = "SamplerWorkflow",
            Title = "Sample",
            Description = "Dummy workflow to test workflow processor.",
            Route = ""
          }
        }
      };
    }
```

on startup.cs But i dont get my workflow in client and get error that JSON is invalid. Where i forgot to register my workflow? 
Thanks
Sincerly Mike!

**Comment by determinate** [comment]
Hello one more question, how to upload files with this angular. THank you

**Comment by thomasduft** [comment]
Hi there
You can not out of the box upload files with the samples I provided. There is no such use case implemented. You need to do that on your own.

If you search for "upload file angular" with google you will find plenty of blog posts that describe your use case.

Greets Thomas

**Comment by determinate** [comment]
Thank you, I found It and added. And changed some functions to Formdef. So i want to know, how I can set value of hidden value, and change viewmodel dynamically? for example onchange add only one parameter?

**Comment by thomasduft** [comment]
Hi
What you typically do in an angular application is to assign/bind a new object with the adjusted/modified properties to the component. The component will then automatically reflect that due to the angular way of detecting changes.

**Notice**: You should not mix and match your questions/issues. This question belongs to my [formdef ](https://github.com/thomasduft/formdef) repository (it is an angular related question) and is not an issue at all for this repository. You opened this issue because of having problems with "dynamic users". Thanks in advance for respecting that.

Greets Thomas
