### ISSUE TITLE
how to use formdef for file

### ISSUE THREAD

**Issue by determinate** [thomasduft/microwf#7]
How to use formdef for input type="file" ? so i cannot ound this. I define in model File type, and add input type=file, but i cannot see file in form? hwo i do this?

**Comment by thomasduft** [comment]
Hi
Well you can not! There is no "FileInput" editor implemented. Feel free to create a PR in the [formdef](https://github.com/thomasduft/formdef) repository. I would appreciate this.
Thanks in advance.
