### ISSUE TITLE
enable see history from others

### ISSUE THREAD

**Issue by determinate** [thomasduft/microwf#8]
how enable to see your workflow, after dispacthing to others, and control all process? it might be seen or not? thank you

**Comment by thomasduft** [comment]
Hi determinate
If I get you right then this kind of feature is very entity related and cannot be out of the box provided. You would basically need a `Creator` column on your entity that you can query. The api would then return all entities where the `Creator` column matches the current user or sth. like this. This would allow to have a list of workflows of that entity that the user has opened/started but possible for the moment being is not responsible for. 
Greets Thomas
